# Generated by Django 6.0.6 on 2026-07-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('engine', 'Двигатель'), ('body', 'Кузов'), ('interior', 'Салон'), ('suspension', 'Подвеска'), ('exhaust', 'Выхлоп'), ('wheels', 'Диски и шины')], max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('duration_days', models.IntegerField(help_text='Срок выполнения в днях')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
